services:
    ingress:
        build: ./ingress
        ports: 
            - "8080:80"
        links:
            - api
            - web
        volumes: 
            - ./ingress/etc/nginx:/etc/nginx/conf.d
            - ./data/ingress:/data/
    
    web:
        build: ./frontend
        working_dir: /app
        command: ["bash", "./start-dev.sh"]
        volumes:
            - ./frontend:/app
        expose:
            - 3000

    api:
        build: ./backend
        expose:
            - 80
        environment:
            - RUN_ENV=DEVELOPMENT
        volumes:
            - ./backend:/app
            - ./data/backend:/app/data

    minio: 
        image: quay.io/minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment: 
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minioAccEducacion
        command: server /data --console-address ":9001"
        volumes:
            - ./data/minio:/data
